#!/bin/bash
set -u

[ "$#" -eq 3 ] || {
	echo "Usage: action from_file to_file" >&2
	exit 1
}

action="$1" ; shift
from_file="$1"; shift
to_file="$1"; shift

if [ "$action" == "encrypt" ]; then
	cat "$from_file" | rev > "$to_file" || exit 1
elif [ "$action" == "decrypt" ]; then
	cat "$from_file" | rev > "$to_file" || exit 1
else
	echo "Error: Unknown action \"$action\"" >&2
	exit 1
fi
